image: node:22-alpine

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  only: 
    - develop
    - main
    - merge_requests

build_project:
  stage: build
  script:
    - export | grep NEXT_PUBLIC
    - npm run build
  only: 
    - develop
    - main
    - merge_requests