image: node:22-alpine

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  only: 
    - develop
    - main
    - merge_requests

build_project:
  stage: build
  script:
    - export | grep NEXT_PUBLIC
    - npm run build
  only: 
    - develop
    - main
    - merge_requests
  
deploy_vercel:
  stage: deploy
  image: node:22-alpine
  only: 
    - develop
    - main
  script:
    - npm install --global vercel
    - vercel link --yes --project $VERCEL_PROJECT_NAME --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID
    - |
      if [ "$CI_COMMIT_BRANCH" == "main" ]; then
        vercel pull --yes --environment=production --token=$VERCEL_TOKEN
        vercel build --prod --token=$VERCEL_TOKEN
        vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
      else
        vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
      
      
        vercel build --token=$VERCEL_TOKEN
        vercel deploy --prebuilt --token=$VERCEL_TOKEN
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"