image: node:22-alpine

stages:
  - install
  - deploy

cache:
  paths:
    - node_modules/
    - .vercel/

install_dependencies:
  stage: install
  script:
    - npm install
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"
  
deploy_vercel:
  stage: deploy
  image: node:22-alpine
  script:
    - npm install --global vercel
    - |
      if [ "$CI_COMMIT_BRANCH" == "main" ]; then
        echo "🚀 Produção Direta"
        vercel deploy --prod --yes --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID
      else
        echo "🛠️ Preview Direta"
        vercel deploy --yes --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"